version: '3.8'

services:
  postgresql:
    image: postgres:14
    container_name: test_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: test_root
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_pg
      TZ: "UTC"
      PGTZ: "UTC"
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
volumes:
  postgres-data: