version: '3.8'

services:
  postgresql:
    image: postgres:14
    container_name: board_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: board_root
      POSTGRES_PASSWORD: board_password
      POSTGRES_DB: board_pg
      TZ: "UTC"
      PGTZ: "UTC"
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
volumes:
  postgres-data: